package cc.modlabs.ktale.entitystats

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe

class EntityStatTypeTest : FunSpec({
    test("id() matches expected Hytale-style PascalCase") {
        EntityStatType.AMMO.id() shouldBe "Ammo"
        EntityStatType.HEALTH.id() shouldBe "Health"
        EntityStatType.MANA.id() shouldBe "Mana"
        EntityStatType.STAMINA_REGEN_DELAY.id() shouldBe "StaminaRegenDelay"
        EntityStatType.DEPLOYABLE_PREVIEW.id() shouldBe "DeployablePreview"
        EntityStatType.GLIDING_ACTIVE.id() shouldBe "GlidingActive"
    }

    test("fromId() resolves ids generated by id()") {
        for (t in EntityStatType.entries) {
            EntityStatType.fromId(t.id()) shouldBe t
        }
    }

    test("fromId() returns null for unknown ids") {
        EntityStatType.fromId("NotARealStat") shouldBe null
        EntityStatType.fromId("") shouldBe null
    }
})

