kind: pipeline
type: docker
name: build

when:
  event:
    - pull_request
  branch:
    - main

steps:
  - name: build
    image: eclipse-temurin:21-jdk
    commands:
      - chmod +x ./gradlew
      - ./gradlew build --stacktrace --no-daemon



